name: DAST Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build and start app with Docker Compose
        run: |
          docker compose up -d
          # Wait for the app to be healthy (adjust as needed)
          sleep 30

      - name: Check running containers
        run: docker ps

      - name: Run ZAP Baseline Scan as root
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080'
          docker_user: 'root'

      - name: Stop and clean up Docker Compose
        if: always()
        run: docker compose down
